//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RZDKursovoy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class PersonalData : global::System.Configuration.ApplicationSettingsBase {
        
        private static PersonalData defaultInstance = ((PersonalData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PersonalData())));
        
        public static PersonalData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RZD")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string DataSource {
            get {
                return ((string)(this["DataSource"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyG7tEIig4phHw
husyD7hbcjPdtznuF6uOzv9W/HjHoNUGdEqarbcRmovOmWr9PywF3iIn1EsMoPsf
A4mWhZPNS+OeRcmL88onN4LGabr1V5pego+oxrgyjTA3KxO7lNpqmS4AheDL39++
yi58yISF7G37U4E8QiNnzhNSmRGlcUdz+ClrD9a6030xO11MBwYzFhoxvE5tx/q6
o3oeQzZB9S87om0lCXRQBSMoMYiOBrW6ddv/kILZRJdeVXlRO/IiXm3TGFQelDhjSCz
0Miy849e/tuLaxYx0fL2W787IkjXheMKD/ikPs3ys9mwjpZfS9PGbrfI40aSkDHdK
GukujzQt/JLgs6J877Ak1w9Gfqe6+H6BHlVeaHEBAoGBAKQGK/hC0pd5XlV/Vw0c
eU0JpBxAZ3H4qScGPt2rm+t4QxLh9U13EHI16DZSNuvG5Q/D053UCed9QXwMTl0K
H/y9+Sb9Hva5LTVoRJXRxAvUz/QCetN4VygoDfPDffq0OUwVwEOHEMpUIShNT4yWm
chSfdcG62zdY4wn9H5N+c9HsJq
-----END PRIVATE KEY-----
")]
        public string KeySi {
            get {
                return ((string)(this["KeySi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RegMaster")]
        public string RegLogin {
            get {
                return ((string)(this["RegLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RegMasterPassword")]
        public string RegPassword {
            get {
                return ((string)(this["RegPassword"]));
            }
        }
    }
}
